data:
  raw_data: "data/dataset.csv"

dates:
  peak:       "2021-09-11"   # portfolio rebalance
  trough:     "2022-11-21"   # portfolio rebalance → Part2/3
  crash_end:  "2024-03-07"   # shading for EDA plots in Part1

windows:
  lookback:     250
  rolling_corr: 30

paths:
  log_returns_csv: "/Users/mitrylitvin/School/EPFL/fin413/fin413-project-a/output/log_returns.csv"
  cov_pp:          "/Users/mitrylitvin/School/EPFL/fin413/fin413-project-a/output/cov_PP.csv"
  cov_tr:          "/Users/mitrylitvin/School/EPFL/fin413/fin413-project-a/output/cov_Tr.csv"
  cleaned_cov_pp:  "/Users/mitrylitvin/School/EPFL/fin413/fin413-project-a/output/cleaned_cov_PP.npy"
  cleaned_cov_tr:  "/Users/mitrylitvin/School/EPFL/fin413/fin413-project-a/output/cleaned_cov_Tr.npy"